#!/usr/bin/env bash


repo_url="https://github.com/eliranmal/styli.sh"

d_usage_line() {
	case $FORMAT in
		markdown)
			sed -e 'N' -e 's,usage:\(.*\)\(\n\)$,\2    \1\2\2,'
			;;
	esac
}

d_gen_message() {
	case $FORMAT in
		markdown)
			printf "%s\n\n\n\n%s\n%s\n%s" "$(cat -)" '<br/><br/>' '---' \
			'<sup><i>formatted with <b><a href="'"$repo_url"'">styli.sh</a></b></i></sup>'
			;;
		raw)
			printf "%s\n\n\n\n\n%s\n%s" "$(cat -)" '---' 'formatted with styli.sh ('"$repo_url"')'
			;;
	esac
}

d_eof() {
	case $FORMAT in
		markdown)
			echo "$(cat -)" # add newline at end of file
			;;
	esac
}

d_dress_up() {
    d_usage_line | d_gen_message | d_eof
}

d_dress_up