#!/usr/bin/env bash


# todo - eat our own dog food, output all usage of this repo to our own './usage' dir, and use it as a showcase :)


main() {

	local source_dir="$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )"

	# todo - if $BASH_SOURCE == $0 we're executing dox, not including it: parse "-h" and show usage

	#echo "> > > source_dir: $source_dir"
	#echo "> > > BASH_SOURCE: $BASH_SOURCE"
	#echo "> > > arg 0: $0"
	#echo "> > > arg 1: $1"
	#echo "> > > args: $@"


	# include the libs

	source "$source_dir"/formatter
	cmd_init_formatter

	if [[ -n $RENDER ]]; then
		source "$source_dir"/renderer
		cmd_init_renderer
	fi
}


main
