#!/usr/bin/env bash


show_help() {
	# eat our own dog food
	printf "
$(t_heading "styli.sh" | t_fg_yellow)

text formatter and renderer for the shell.


$(t_subheading "flags")

$(t_code_definition \
"-h" \
"shows this help message." \
)

"
	exit 0
}

main() {

	local source_dir="$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )"

	source "$source_dir"/formatter
	source "$source_dir"/renderer

	# test if this script is executed (i.e. not sourced)
	if [[ $BASH_SOURCE = $0 && $1 = "-h" ]]; then
		show_help
	fi
}


main "$@"
