#!/usr/bin/env bash


#$(t_heading $(t_fg_blue "styli"$(t_fg_yellow ".sh")))

show_help() {
	# eat our own dog food
	printf "
$(t_heading "styli.sh" | t_fg_yellow)

text formatter and renderer for the shell.


$(t_subheading "flags")

$(t_code_definition \
"-h" \
"shows this help message." \
)

"
	exit 0
}

# test if this script is executed (i.e. not sourced)
is_executed() {
	[[ $BASH_SOURCE = $0 ]]
}

main() {

	local source_dir="$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )"

	source "$source_dir"/formatter
	cmd_init_formatter

	if [[ -n $RENDER ]]; then
		source "$source_dir"/renderer
		cmd_init_renderer
	fi

	if is_executed && [[ $1 = "-h" ]]; then
		show_help
	fi
}


main "$@"
